### ISSUE TITLE
Question on Commit #724

### ISSUE THREAD

**Issue by markofu** [Security-Onion-Solutions/securityonion-rule-update#2]
Hey Doug,

Looking at the commit "https://github.com/Security-Onion-Solutions/securityonion-rule-update/commit/80383559525982ed87b358f6bd8d374d2a29a804#diff-aa5f7326231812d7d56aeafa20e694c6L213", there's a change to the code whereby the sensor will sleep for 60 minutes if the _rule_update_ command isn't run interactively.

This appears to result in causing a rule update from _salt_ (being run on the server):

```
sudo salt '*' cmd.run  rule-update
```

to be delayed by 60 minutes:

```
Cleaning up downloaded.rules backup files older than 30 days.
Backing up current local.rules file before it gets overwritten.
Cleaning up local.rules backup files older than 30 days.
Sleeping for 60 minutes to allow master time to download new rules.
Copying rules from *.*.*.*.
```

As a result, the update command takes over an hour to run:

```
real    62m52.827s
user    0m54.806s
sys     0m6.873s
```

There's the check to see if the command is run interactively by checking the exit code of

```
tty -s
```

as shown at https://github.com/Security-Onion-Solutions/securityonion-rule-update/blob/80383559525982ed87b358f6bd8d374d2a29a804/usr/bin/rule-update#L223. This check appears to equal 1 (logically) for the update via _salt_.

My question: "Is the above the expected behaviour?" for when running the _rule-update_ command via _salt_? 

Apologies if this isn't the best place to log issues or requests, if there's a better place, please let me know.

Thanks

**Comment by dougburks** [comment]
Hi markofu,

When you're running salt, you don't need to run `sudo salt '*' cmd.run  rule-update` at all.  Salt automatically replicates rulesets every 15 minutes.  If you want to force it to replicate immediately, you can do `sudo salt '*' state.highstate`

Also see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Salt

If you have further questions or problems, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

**Comment by markofu** [comment]
Thanks @dougburks.

I had an idea, I missed something - cheers for the extra context and info :)
