### ISSUE TITLE
Management server overload with multiple sensors - sguil latency error.

### ISSUE THREAD

**Issue by mattmeer** [Security-Onion-Solutions/securityonion-rule-update#6]
Hello Doug,

I have been running security onion for quite a while now and have noticed that when running a setup that has 20+ sensors connecting to a management server overloads the server during the rule-update. This will cause a sguil latency error to be thrown because the sensors can't connect to the management server on time. I looked into the rule-update script and noticed that you take a random time for the script to be executed on the management server (line 137 to 142), to avoid overloading the rule vendors, but you don't do this on the sensors. I think that also having the sensors connect to the management on a random time would solve this issue.

Kind regards

**Comment by dougburks** [comment]
Hi @mattmeer ,

The random delay on the server side was added to prevent the THOUSANDS of Security Onion deployments hitting the rule sites at the same time.  I'm a little surprised that only 20 sensors copying a file from your master server would cause an issue.  Can you provide more details about the "sguil latency error"?

Also, most deployments are no longer using the traditional rule-update for syncing rules from the master to the sensors.  Have you considered switching to onionsalt?
https://github.com/Security-Onion-Solutions/security-onion/wiki/Salt

**Comment by mattmeer** [comment]
Hello Doug,

Essentially it is because all the services restart on every sensor at the same time that sometimes it can't seem to connect to the management server, example:
In /var/log/nsm/[hostname here]-eth1/snort_agent-1.log it will log the following:
"Unable to connect to [management_server here] on port 7736."
In this case the service failed connect because the management server got overloaded with requests from the other sensors. This causes data that is supposed to be send to the management server to be kept on the sensor and when/if the sensor manages to make a connection to the management server, it will cause the logs to be send in with a delay (this can go up to several hours). This causes some of the checks I have in place on sguil to throw an error that the logs aren't synchronized. I have looked at your code and i think simply moving the random time sleep IF before the management server check IF would solve this issue.

Kind regards.

**Comment by dougburks** [comment]
I'm still not sure that the symptom you're describing is due to your sensors copying a file, as it should not be that resource intensive.

How many uncategorized events do you have in Sguil?  You can check by running the following command on your master server:
```
sudo mysql --defaults-file=/etc/mysql/debian.cnf -Dsecurityonion_db -e "SELECT COUNT(*) FROM event WHERE status=0"
```

If you have a high number of uncategorized events, that could cause a delay when the master server restarts sguild, which could then result in the symptom that you're seeing.

**Comment by mattmeer** [comment]
Hello Doug,

Here is the result:
+----------+
| COUNT(*) |
+----------+
|   104828 |
+----------+
That seems pretty high, if this wasn't the issue what solution would you suggest?

Kind regards.

**Comment by dougburks** [comment]
Yes, that is high, and that is most likely what is causing the symptoms that you are describing.  

From https://github.com/Security-Onion-Solutions/security-onion/wiki/PostInstallation:

> Review and categorize events every day with the goal being to categorize all events every day. Neglecting to do so will result in database/Sguil issues as the number of uncategorized events continues to increase on a daily basis.

You should log into Sguil/Squert every day and try to categorize all events.  Note that categorizing doesn't remove events from the database, it simply marks them with a particular categorization.  If you can get that number down to a more manageable level, then sguild should start up much faster in the morning and your sensors should be able to connect just fine.

For more information, please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/ManagingAlerts
